# iniciando com ci

image: docker:stable

services:
- docker:dind

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 

build-docker:
  stage: build
  script:
  - docker build -t minha-imagem .
  - docker pull minha-imagem:latest || true
  - docker tag minha-imagem:latest minha-imagem:latest
  - docker push jnlucas/minha-imagem:latest
