image: docker:stable

stages:
- pre-build
- build
- test
- deploy

services:
- docker:dind 

before_script:
- docker info
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build-docker:
  stage: pre-build
  script:
  - docker build -t minha-imagem .
  - docker tag minha-imagem jnlucas/minha-imagem:latest
  - docker push jnlucas/minha-imagem:latest

build-project:
  stage: build
  dependencies:
  - build-docker
  tags:
  - executor-tarefas
  script: 
  - echo "runner"














