# iniciando com ci

before_script:
  - sudo apt-get remove docker docker-engine
  - sudo curl -sSL https://get.docker.com/ | sh
  - sudo rm /usr/local/bin/docker-compose
  - docker info


build-docker:
  stage: build
  script:
  - docker build -t minha-imagem .
