# iniciando com ci

image: docker:stable
stages:
  - pre-build
  - build
  - test
  - deploy

services:
  - docker:dind
  - mysql:5.7
variables:
  MYSQL_USER: devops_dev
  MYSQL_PASSWORD: mestre
  MYSQL_DATABASE: todo_dev
  MYSQL_ROOT_PASSWORD: senha

  SECRET_KEY: 'r*5ltfzw-61ksdm41fuul8+hxs$86yo9%k1%k=(!@=-wv4qtyv'
  DB_NAME: 'todo_dev'
  DB_USER: 'devops_dev'
  DB_PASSWORD: 'mestre'
  DB_HOST: 'mysql'
  DB_PORT: '3306'


build-docker:
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

  stage: pre-build
  script:
  - docker build -t minha-imagem .
  - docker tag minha-imagem jnlucas/minha-imagem:latest
  - docker push jnlucas/minha-imagem:latest

build-project:
  stage: build
  tags:
  - meu-job
  dependencies:
  - build-docker

  script:
  - python manage.py makemigrations
  - python manage.py migrate
