# iniciando com ci

image: docker:stable

services:
- docker:dind

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build-docker:
  stage: build
  script:
  - docker build -t minha-imagem .
  - docker tag minha-imagem minha-imagem:1.0.0
  - docker push jnlucas/minha-imagem:latest
