# iniciando com ci

before_script:
  - curl -sSL https://get.docker.com/ | sh
  - rm /usr/local/bin/docker-compose
  - docker info


build-docker:
  stage: build
  script:
  - docker build -t minha-imagem .
