version: '3'

services:
  db: 
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: 'devops_dev' 
      MYSQL_PASSWORD: 'mestre' 
      MYSQL_DATABASE: 'todo_dev' 
      MYSQL_ROOT_PASSWORD: 'senha'
  web:
    image: jnlucas/minha-imagem:latest
    volumes:
      - ./env:/usr/src/app/to_do/.env 
    ports:
      - "8001:8001"
    depends_on: 
      - db
